repos:
  - repo: local
    hooks:
      - id: gleam-format
        name: gleam format
        entry: gleam format
        language: system
        files: ^(src|test)/.*\.gleam$
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      - id: ruff-format
